version: '3'
services:
  postgres:
    container_name: yanodam-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5434:5432
    networks:
      - app-network

  test-db:
    container_name: yanodam-test-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5435:5432
    networks:
      - app-network

  redis:
    container_name: yanodam-redis
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_DB=0
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redis
    networks:
      - app-network

  mongo:
    container_name: yanodam-mongo
    image: mongo:latest
    ports:
      - '27017:27017'

networks:
  app-network:
    driver: bridge

volumes:
  data:
