services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5434:5432
    networks:
      - default

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_DB=0
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redis
    networks:
      - default
